name: Selenium E2E login test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: Install Dependencies
      run: |
        npm install
        cd automated_test
        npm install

    - name: Install Google Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Build Web Application
      run: npx expo export --platform web

    - name: Start Dev Server
      run: |
        CI=1 npx expo start --web &
        npx wait-on -t 120000 http://localhost:8081
        echo "Expo Web Server is ready!"

    - name: Run E2E Selenium Tests
      continue-on-error: true
      run: node automated_test/selenium/selenium_test.js > automated_test/selenium_terminal_log.txt 2>&1

    - name: Upload Test Report and Logs
      uses: actions/upload-artifact@v4
      with:
        name: selenium-test-results
        path: |
          automated_test/selenium_report.xlsx
          automated_test/selenium_terminal_log.txt
        retention-days: 5
